version: '3.8'

services:
  api:
    restart: always
    build: ./api
    depends_on:
      - postgres
      - elastic
    env_file:
      - .env
    networks:
      - ms
    ports:
      - 1337:22808

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRE_USER}
      - POSTGRES_PASSWORD=${POSTGRE_PASS}
      - POSTGRES_DB=${POSTGRE_DBNAME}
    networks:
      - ms

  elastic:
    image: elasticsearch:8.13.0
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - ms
    ports:
      - 54321:9200

networks:
  ms:
    driver: bridge